-- ISR Site-in-a-Box: schema + seed data for Supabase (Postgres)
-- Generated from the site's bundled data.js so the first live sync exactly
-- matches what's on the site today. Run this once in the Supabase SQL editor.

-- ============================================================
-- 1. TABLES
-- ============================================================

create table if not exists equipment (
  id text primary key,
  category text not null,
  item text not null,
  vendor text,
  default_qty integer not null default 0,
  unit_weight numeric not null default 0,
  unit_volume numeric not null default 0,
  -- Shipping-case outer dimensions in inches, as measured with a tape
  -- measure. Optional and purely a convenience for deriving unit_volume
  -- (L*W*H / 1728 = cu ft) in the Admin panel - not used anywhere in the
  -- packing/capacity math itself, which only ever reads unit_volume and
  -- unit_weight. Weight is never derived from these; it must still be
  -- entered directly from a scale reading.
  length_in numeric,
  width_in numeric,
  height_in numeric,
  transport text,
  container text not null,
  pros text,
  cons text,
  notes text,
  source text,
  sort_order integer not null default 0,
  updated_at timestamptz not null default now()
);

-- Safe to re-run: adds the dimension columns to an equipment table that was
-- already created by an earlier version of this script.
alter table equipment add column if not exists length_in numeric;
alter table equipment add column if not exists width_in numeric;
alter table equipment add column if not exists height_in numeric;

create table if not exists power_load_items (
  id text primary key,
  label text not null,
  typical_w numeric not null default 0,
  max_w numeric not null default 0,
  qty numeric not null default 0,
  qty_editable boolean not null default false,
  notes text,
  sort_order integer not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists antenna_comparison (
  id bigint generated always as identity primary key,
  system text not null,
  architecture text,
  band_coverage text,
  orbital_regimes text,
  pack_form text,
  acquisition text,
  pros text,
  cons text,
  source text,
  sort_order integer not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists radome_comparison (
  id bigint generated always as identity primary key,
  system text not null,
  structure_type text,
  continuous_power text,
  setup_time text,
  pros text,
  cons text,
  source text,
  sort_order integer not null default 0,
  updated_at timestamptz not null default now()
);

-- ============================================================
-- 2. ROW LEVEL SECURITY: public read-only, single admin can write
-- ============================================================
-- After creating your one admin user in Supabase Auth, copy their
-- UID (Authentication -> Users) and replace the placeholder below,
-- then run just this section again (safe to re-run).

alter table equipment enable row level security;
drop policy if exists "equipment_public_read" on equipment;
create policy "equipment_public_read" on equipment for select using (true);
drop policy if exists "equipment_admin_write" on equipment;
create policy "equipment_admin_write" on equipment for all using (auth.uid() = '00000000-0000-0000-0000-000000000000') with check (auth.uid() = '00000000-0000-0000-0000-000000000000');

alter table power_load_items enable row level security;
drop policy if exists "power_load_items_public_read" on power_load_items;
create policy "power_load_items_public_read" on power_load_items for select using (true);
drop policy if exists "power_load_items_admin_write" on power_load_items;
create policy "power_load_items_admin_write" on power_load_items for all using (auth.uid() = '00000000-0000-0000-0000-000000000000') with check (auth.uid() = '00000000-0000-0000-0000-000000000000');

alter table antenna_comparison enable row level security;
drop policy if exists "antenna_comparison_public_read" on antenna_comparison;
create policy "antenna_comparison_public_read" on antenna_comparison for select using (true);
drop policy if exists "antenna_comparison_admin_write" on antenna_comparison;
create policy "antenna_comparison_admin_write" on antenna_comparison for all using (auth.uid() = '00000000-0000-0000-0000-000000000000') with check (auth.uid() = '00000000-0000-0000-0000-000000000000');

alter table radome_comparison enable row level security;
drop policy if exists "radome_comparison_public_read" on radome_comparison;
create policy "radome_comparison_public_read" on radome_comparison for select using (true);
drop policy if exists "radome_comparison_admin_write" on radome_comparison;
create policy "radome_comparison_admin_write" on radome_comparison for all using (auth.uid() = '00000000-0000-0000-0000-000000000000') with check (auth.uid() = '00000000-0000-0000-0000-000000000000');

-- ============================================================
-- 3. SEED DATA (current site content, one INSERT per row)
-- ============================================================
truncate equipment, power_load_items, antenna_comparison, radome_comparison;

insert into equipment (id, category, item, vendor, default_qty, unit_weight, unit_volume, length_in, width_in, height_in, transport, container, pros, cons, notes, source, sort_order) values
  ('eq-01-ant-mechanically-positio', 'Antenna & Tracking Systems', 'Mechanically-Positioned Dish, Quick-Change Feed Architecture (threshold 2 / objective 3 dishes)', 'AvL 1.8-2.4m Quad-Band Motorized Flyaway/Vehicular family (palletized C/X/Ku/Ka feeds)', 3, 350, 40, NULL, NULL, NULL, 'Ships as a multi-case set, ISU-90', 'Container 1 - Antenna & RF', 'Palletized feed design lets one crew swap C, X, Ku, or Ka feed packages on the same dish/pedestal in the field in minutes rather than needing a dedicated aperture per band; carbon-fiber reflector keeps pack weight down; auto-acquisition positioner tracks GEO/MEO/LEO/HEO', 'Only one band is live on a given dish at a time - covering multiple bands simultaneously means dedicating separate dishes to separate bands rather than one dish doing everything at once', 'digisat.org AvL 2460/2020 and 1810-series product pages. This is the primary recommended architecture per the swap-based approach - mechanically change 2-3 apertures/feeds rather than one simultaneous multi-band feed.', 'digisat.org (AvL)', 0),
  ('eq-02-ant-quick-change-feed-pa', 'Antenna & Tracking Systems', 'Quick-Change Feed Pallet Set (C, X, Ku, Ka - 4 pallets per antenna)', 'AvL palletized feed pallets, band-specific', 8, 35, 3, NULL, NULL, NULL, 'Cased with antenna set, ISU-90', 'Container 1 - Antenna & RF', 'Each pallet swaps in without tools, is individually cased, and can be pre-staged so a band change is a field-level task, not a depot task', 'A full feed inventory (4 pallets x however many dishes carry more than one band) adds real case count and spares burden', 'digisat.org AvL feed-pallet descriptions. Qty shown (8) covers 2 dishes x 4 bands; scale to 12 if all 3 objective dishes are each equipped with the full C/X/Ku/Ka pallet set.', 'esatcom.com (AvL feeds)', 1),
  ('eq-03-ant-dedicated-s-band-fee', 'Antenna & Tracking Systems', 'Dedicated S-Band Feed/Dish Module (fills the gap the C/X/Ku/Ka swap family doesn''t cover)', 'Dolph Microwave or Comtech-MCT S-band-capable tracking dish/feed', 1, 500, 55, NULL, NULL, NULL, 'Ships as a multi-case set, ISU-90', 'Container 1 - Antenna & RF', 'Both vendors publish explicit S-band coverage with GEO/MEO/LEO/HEO tracking, closing the one gap in the AvL swap family', 'Adds a second product line/spares chain rather than staying within one vendor''s swap ecosystem; heavier than the AvL-class dishes', 'dolphmicrowave.com and sky-brokers.com Comtech-MCT pages. Treat as an RFI item - ask both the AvL-style vendor and these S-band vendors whether an S-band feed pallet can be engineered into the same swap architecture instead.', 'dolphmicrowave.com', 2),
  ('eq-04-ant-electronically-steer', 'Antenna & Tracking Systems', 'Electronically Steered Array (ESA) Flat-Panel Antenna - Ku/Ka alternative', 'Kymeta KuKa 8 Series (simultaneous Ku/Ka, single aperture, no moving parts)', 0, 60, 4, NULL, NULL, NULL, 'ISU-90', 'Container 1 - Antenna & RF', 'No mechanical positioner at all - electronic beam steering switches between GEO/MEO/LEO/HEO and between Ku/Ka simultaneously in a single low-profile panel, cutting SWaP versus a dish-plus-feed-swap approach for those two bands', 'As of its 2026 ONR development contract this is an emerging capability, not yet a fielded program of record; panel-based designs generally cover a narrower band range than a feed-swappable dish', 'kymetacorp.com / defence-blog.com KuKa 8 Series coverage. Offered as the ''panel-technology'' alternative named in the requirement - qty 0 pending a maturity/availability decision versus the AvL dish approach.', 'kymetacorp.com', 3),
  ('eq-05-ant-electronically-steer', 'Antenna & Tracking Systems', 'Electronically Steered Array (ESA) Flat-Panel Antenna - conformal alternative', 'NexSat ACE (Aero Conformal ESA), Ku/Ka', 0, 50, 3, NULL, NULL, NULL, 'ISU-90', 'Container 1 - Antenna & RF', 'Fully conformal embedded design ("The Invisible Antenna") could mount flush to a shelter or vehicle panel rather than needing its own pedestal footprint', 'Newly unveiled product (2026); track record and government fielding history are both thin', 'microwavejournal.com Satellite 2026 coverage. Listed as a second ESA option for the panel-technology path, qty 0.', 'microwavejournal.com', 4),
  ('eq-06-ant-2-4m-mocat-flyaway-m', 'Antenna & Tracking Systems', '2.4m MOCAT Flyaway/Mobile Tracking Antenna', 'CPI Antenna Technologies MOCAT ("MOCAT Open" config), part of CPI''s 0.6-2.4m flyaway family', 0, 450, 50, NULL, NULL, NULL, 'Multi-case transportable set, ISU-90', 'Container 1 - Antenna & RF', 'Purpose-built defense/connectivity flyaway from a long-established earth-station manufacturer; shown at AFCEA defense trade events specifically as a 2.4m MOCAT; shares a design language with CPI''s broader 0.6-2.4m flyaway line', 'Public marketing material emphasizes X-band; full S/C/Ku/Ka feed-swap availability on this specific model isn''t confirmed in public sources - verify directly with CPI', 'cpii.com Flyaway Antennas pages (0.6m/1.2m/2.4m); CPI Vertex Antennentechnik AFCEA show post referencing the 2.4m MOCAT. CPI now also owns the former GD SATCOM Technologies brands - see next row.', 'cpii.com (CPI)', 5),
  ('eq-07-ant-2-4m-4-piece-antenna', 'Antenna & Tracking Systems', '2.4m 4-Piece Antenna, Dual-Axis Tracking Mount (Prodelin/VertexRSI legacy line)', 'General Dynamics SATCOM Technologies / Prodelin (brand now under CPI SAT, formerly "GD Satcom Technologies & Prodelin")', 0, 500, 55, NULL, NULL, NULL, 'Multi-case transportable set, ISU-90', 'Container 1 - Antenna & RF', 'Deep TT&C/earth-station heritage under the VertexRSI/Gabriel/Prodelin names; the related 4.6m sibling model offers palletized, field-swappable C-through-Ka feeds changeable in minutes - likely the same design language at 2.4m', 'GD SATCOM Technologies has been absorbed into CPI SAT - this and the CPI MOCAT row above may not be independent competitors anymore. Confirm current corporate/brand separation before treating them as two separate bids.', 'digisat.org GD SATCOM Technologies 4.6m Mobile Earth Station page; Prodelin 4096-536 2.4m 4-piece assembly manual; digisat.org CPI SAT O3b 2.4m Ka-band terminal page (confirms the CPI SAT rebrand).', 'digisat.org (GD/CPI SAT)', 6),
  ('eq-08-ant-2-4m-class-full-limi', 'Antenna & Tracking Systems', '2.4m-class Full/Limited-Motion Earth Station Antenna', 'Viasat Antenna Systems, remote-sensing/ISR earth-station line (2.4m-24m range)', 0, 550, 60, NULL, NULL, NULL, 'Multi-case/transportable, ISU-90 (at the smaller end of the range)', 'Container 1 - Antenna & RF', 'Vendor explicitly markets this line for ISR missions across GEO/HEO/MEO/LEO tracking; large-scale earth-station manufacturer with hundreds of remote-sensing antennas fielded worldwide', 'Public product literature doesn''t break out a specific 2.4m or 3m model by name/spec sheet - sizing within the 2.4-24m range needs a direct vendor quote', 'viasat.com/government/antenna-systems (explicit ISR framing, 2.4m-24m range); vicmyers.com Viasat antenna systems page.', 'viasat.com', 7),
  ('eq-09-ant-multi-mission-termin', 'Antenna & Tracking Systems', 'Multi-Mission Terminal (MMT) - flyaway, feed-arm band swap (below stated dish-size floor)', 'Viasat MMT', 0, 150, 20, NULL, NULL, NULL, 'Transportable cases, ISU-90', 'Container 1 - Antenna & RF', 'Feed-arm swap covers commercial Ku, WGS Ka, ViaSat-1/2 Ka, and commercial X-band on one terminal; sets up in under 30 minutes; built for A2AD network roaming resilience', 'Smaller-class flyaway - public material doesn''t confirm a reflector diameter in the 2.4-3m range, so it likely sits below the stated dish-size floor. Better fit as a comms-backhaul terminal (Communications & Backup Backhaul category) than a collection antenna', 'viasat.com/products/terminals-and-radios/ground-terminals (MMT description).', 'viasat.com (MMT)', 8),
  ('eq-10-ant-2-4m-motorized-flyaw', 'Antenna & Tracking Systems', '2.4m Motorized Flyaway Antenna (Agilis carbon fiber)', 'Sat-Lite Technologies Model 2431/2432, Celero antenna control system', 0, 400, 45, NULL, NULL, NULL, '6 cases + 1 RF case per band, ISU-90', 'Container 1 - Antenna & RF', '9-piece segmented carbon-fiber reflector for high gain/low cross-pol; assembles in 15 minutes; C/X/Ku production models; won a $9.9M US Army COTS tactical-aperture contract (July 2026, Aberdeen Proving Ground) - fresh, direct Army sustainment relevance', 'Published band coverage for the 2431/2432 line is C/X/Ku - Ka and S are not confirmed on this line and need vendor confirmation', 'digisat.org Sat-Lite 2432 page; Sat-Lite Model 2431 page; satnews.com, July 13 2026, Sat-Lite $9.9M Army SATCOM contract (W911SR-26-D-SATL, Aberdeen Proving Ground).', 'digisat.org (Sat-Lite)', 9),
  ('eq-11-ant-3-7m-flyaway-antenna', 'Antenna & Tracking Systems', '3.7m Flyaway Antenna (above stated 3m ceiling - included for reference)', 'Ultra I&C FA-370 family (FA-370/60, /70, /140, /180, /300)', 0, 1020, 20, NULL, NULL, NULL, '5 cases, ISU-90', 'Container 1 - Antenna & RF', 'Quad-band feed arm (C/X, Ku/DBS, Ka - clipped in and changed in minutes, same swap philosophy as the AvL/GD lines) on one of the largest true flyaway apertures on the market; 3.7m diameter drives materially higher gain (45-58 dBi depending on band) than the 2.4m-class systems, which directly helps the 9-12 dB SNR margin; linear polarization standard with circular optional; MIL-STD-810G certified and WGS/SkyNet/XTAR/Inmarsat compliant; assembles in <30 min, no tools, 5 cases totaling ~470 kg (~1,036 lb)', 'Diameter exceeds the stated 2.4-3m ceiling by 0.7m, and the 5-case set is heavier/bulkier than the 2.4m-class competitors above; like the AvL/GD swap architecture, no native S-band feed cartridge is published', 'Ultra I&C FA-370 product page and full technical datasheet (ultra-ic.com). Included for reference since it''s directly adjacent to the requested size range and uses the same quick-change-feed philosophy as the primary AvL recommendation - worth a look if the 3m ceiling has any flexibility for the SNR margin it buys.', 'ultra-ic.com (datasheet PDF)', 10),
  ('eq-12-rad-rigid-self-supportin', 'Radome Systems', 'Rigid Self-Supporting Portable Radome (recommended)', 'Walton De-Ice Portable Radome', 3, 98, 12, NULL, NULL, NULL, 'ISU-90', 'Container 2 - Radome & Shelter', 'No continuous blower/power draw (self-supporting), assembles tool-free in under an hour, rated for roughly twice the wind load of comparable inflatable systems, smallest model is airline-baggage-checkable', 'Heavier pack weight than an inflatable envelope of the same aperture; larger sizes still need multiple personnel to erect', 'milsatmagazine.com Walton Portable Radome coverage. Recommended default - keeps the radome off the power/thermal budget (see Power & Thermal Budget tab).', 'milsatmagazine.com', 11),
  ('eq-13-rad-air-supported-infl', 'Radome Systems', 'Air-Supported / Inflatable Radome (alternate) - pressurized & sealed, not continuously blown', 'HDT Global AirBeam RaDome (air-beam structure inflated to ~55 psi, sealed via robust valve)', 0, 60, 6, NULL, NULL, NULL, 'ISU-90', 'Container 2 - Radome & Shelter', 'Lowest pack weight/volume of any radome option; minimally attenuates RF; once inflated to ~55 psi and sealed behind a robust valve it holds pressure without a continuously running blower - removing the standing electrical load and blower-failure risk of a true continuously-blown structure', 'Still needs a high-CFM air source (tankless compressor, or several smaller compressors feeding one valve) to reach full pressure initially and for any periodic top-off - an intermittent, not continuous, requirement, but still a real piece of kit to carry', 'Corrected per program clarification: AirBeam uses a sealed valve at ~55 psi rather than continuous blower operation. See the compressor line below rather than a continuous wattage draw on the Power & Thermal Budget tab.', 'adsinc.com (HDT Global)', 12),
  ('eq-14-rad-high-cfm-inflation-c', 'Radome Systems', 'High-CFM Inflation Compressor (intermittent use, AirBeam-type sealed radome)', 'Tankless/portable high-CFM air compressor (or ganged smaller units) sized to the AirBeam fill-valve spec', 0, 80, 6, NULL, NULL, NULL, 'ISU-90', 'Container 2 - Radome & Shelter', 'Only needed at initial inflation and occasional top-off, not continuously - a much lighter power/maintenance burden than a continuously-running blower', 'Needs to hit the specific CFM/pressure the AirBeam fill valve requires - a generic shop compressor likely won''t cut it', 'Weight/CFM are placeholders - pull the actual compressor spec from HDT Global''s AirBeam data sheet before finalizing. Pairs with the AirBeam radome row above - set qty to 1 if that radome path is selected.', 'N/A - generic category', 13),
  ('eq-15-rad-rigid-space-frame-ra', 'Radome Systems', 'Rigid Space-Frame Radome (extended-deployment alternate)', 'Alaska Defense SkyDome-style geodesic radome', 0, 400, 30, NULL, NULL, NULL, 'Non-ISU / Assembly on site', 'Non-ISU / Separate Transport', 'Most robust weather protection of the three options, well suited to a site expected to stay in place for months', 'Longest, most complex assembly (semi-permanent), least suited to a ''rapidly deployable'' requirement', 'alaskadefense.com SkyDome radar enclosure page. Listed for completeness; not recommended given the rapid-deployment driver.', 'alaskadefense.com', 14),
  ('eq-16-she-expandable-fabric-sh', 'Shelter Systems', 'Expandable Fabric Shelter (ops/analysis floor)', 'HDT Global DRASH; Camel Manufacturing', 1, 800, 60, NULL, NULL, NULL, 'Own transport / Container 2', 'Container 2 - Radome & Shelter', 'Fast erect (~30 min), large usable floor area for 10 operators plus antenna control racks, low cube when struck', 'Fabric less hardened than rigid wall; needs guy-lines/anchoring, more weather-exposed than a rigid shelter', 'HDT Global shelter literature; JSB-ESBE catalog for comparable fabric-shelter erect times.', 'adsinc.com (HDT Global)', 15),
  ('eq-17-she-rigid-wall-expandabl', 'Shelter Systems', 'Rigid-Wall Expandable Shelter (alternate)', 'JSB-ESBE Mobile Expandable Rigid Wall Shelter (MERWS)', 0, 7500, 385, NULL, NULL, NULL, 'Self-contained (own ISO/ISU shelter)', 'Non-ISU / Separate ISO Shelter', 'Better EMI/ballistic protection than fabric, ~1,000-1,150 sq ft floor space, standard ECU interface built in', 'Longer erect time (~4 hrs, 4 soldiers); the whole kit consumes an ISO shelter''s worth of airlift/sealift space', 'JSB-ESBE Expeditionary Shelters & Basing catalog.', 'dsp.dla.mil (JSB-ESBE)', 16),
  ('eq-18-she-entry-control-point', 'Shelter Systems', 'Entry Control Point Module - tent-integrated (recommended)', 'HDT DRASH Self Enclosed Annex Lobby (SEAL) + Hard Door, forming a complete ECP', 1, 120, 15, NULL, NULL, NULL, 'ISU-90', 'Container 2 - Radome & Shelter', 'Purpose-built by the tent manufacturer specifically to form "a complete entry control point" per HDT''s own product language; the SEAL explicitly "maintains blackout and climate conditions," so it shares the ops shelter''s conditioned air with no separate HVAC engineering needed - just a duct/plenum tie-in, not a new zone; the Hard Door''s black, impact-resistant fiberglass face is also harder to detect at night than a soft door', 'Still a fabric-and-fiberglass structure, not a rigid/hardened barrier - if the security plan calls for a more physically robust ECP (forced-entry resistance, ballistic protection), see the ISU-90 ECP alternate below', 'hdtglobal.com HDT DRASH SEAL and Hard Door product pages. Recommended default: simplest, lightest, and explicitly designed for this exact purpose - no custom engineering required.', 'hdtglobal.com (DRASH SEAL)', 17),
  ('eq-19-she-entry-control-point', 'Shelter Systems', 'Entry Control Point Module - ISU-90 vestibule (alternate, more hardened)', 'ISU-90 container + soft connector/boot adapter bridging the container door to the tent door', 0, 1710, 0, NULL, NULL, NULL, 'N/A (is the container)', 'N/A - structural alternate to the SEAL row above', 'Rigid steel structure gives real forced-entry resistance and theft/weather resistance a fabric SEAL can''t match; doubles as lockable storage for a PED locker/access-control panel at the threshold; reuses a container already in the site''s inventory model', 'No off-the-shelf adapter confirmed for bridging an ISU-90 door directly to a DRASH-type tent door - HDT''s Shelter Connector Sets and Design Shelter''s vehicle-interface boot both prove the soft-connector concept works for other geometries, but adapting one to a rigid container opening needs a vendor RFI/custom fabrication before this is a real line item, not a paper one', 'hdtglobal.com HDT DRASH Shelter Connector Sets ("weather and light-tight connection... regardless of series or model"); designshelter.com Vestibules & Connectors (vehicle interface boot as the closest analog). Treat as an engineering RFI, not a turnkey purchase, until a specific adapter is sourced or fabricated.', 'hdtglobal.com (Connector Sets)', 18),
  ('eq-20-she-ecu-duct-extension', 'Shelter Systems', 'ECU Duct Extension / Coupler Kit (shares Zone A HVAC across the shelter + ECP)', 'Standard ECU duct extension, duct bag, and coupler (matches the Zone A ECU''s connection type)', 1, 40, 3, NULL, NULL, NULL, 'ISU-90', 'Container 2 - Radome & Shelter', 'Lets one Zone A ECU (see Power & Thermal Budget tab) condition both the ops shelter and the attached ECP through a single duct run, instead of needing a second dedicated unit for the vestibule', 'Duct routing through the shelter/ECP connector point needs to be planned into the erect sequence, not improvised afterward', 'General ECU accessory category (component type referenced in HDT/Tekgard ECU literature). Confirm coupler size against the specific Zone A ECU model selected.', 'N/A - generic category', 19),
  ('eq-21-she-sensor-container-i', 'Shelter Systems', 'Sensor Container - isolated ISU-90 with integrated HVAC', 'ISU-90 outfitted with equipment racking + dedicated vertical/wall-mount ECU pair (see Environmental Control tab rows)', 1, 1710, 0, NULL, NULL, NULL, 'N/A (is the container)', 'Non-ISU / Sited near antenna array, separate from Container 2', 'Physically isolates the sensor''s server/fan noise from the manned ops floor - operators aren''t sitting next to the loudest, hottest box on site; the steel container shell also acts as an incidental Faraday enclosure, containing the sensor''s own switching-supply/digital RF noise rather than letting it reach the nearby receive antennas, and shielding the sensor''s front end from other site-generated RFI - provided cable entries use filtered/gasketed bulkhead connectors rather than open penetrations; siting it close to the antenna array keeps the RF feed runs short (the same G/T logic as before), while a fiber/network reach-back link (not RF, so far less loss-sensitive) carries data back to the ops shelter consoles, freeing the ops shelter''s location to be chosen for security/personnel reasons instead of RF proximity', 'Adds a fifth structural element to site instead of folding the sensor into an existing shelter; needs its own dedicated HVAC zone (Zone B) sized conservatively to the sensor''s peak draw, not typical, because a sealed steel box has far less thermal buffering than the fabric shelter - see Power & Thermal Budget tab', 'Design pattern generalized from SEA BOX Tricon Insulated Shelter with Climate Control (climate-controlled ISO/Tricon electronics enclosures are an established commercial category) and ACT/Tekgard''s vertical ECU line, which is explicitly built for rigid-wall shelter cooling. Treat as a custom integration: ISU-90 + vertical ECU pair + rack + filtered cable entries, not a single off-the-shelf SKU.', 'seabox.com (design pattern)', 20),
  ('eq-22-pow-60-kw-tactical-quiet', 'Power Generation & Distribution', '60 kW Tactical Quiet Generator (recommended backup)', 'MEP-806A/806B (50/60/400 Hz)', 1, 2500, 0, NULL, NULL, NULL, 'Skid-mounted, own trailer/flatrack', 'Non-ISU / Own Trailer-Skid', 'Carries the full-site max electrical load (sensor + antennas + IT + HVAC) at ~45-50% loading, per the Power & Thermal Budget tab - healthy margin for growth and generator longevity', 'Heaviest/bulkiest generator option; overkill if FOB power is exceptionally reliable and outages are rare', 'TM 9-6115-672-24P; MARCORSYSCOM info sheet. See Power & Thermal Budget tab, Section 4, for the sizing math.', 'marcorsyscom.marines.mil', 21),
  ('eq-23-pow-30-kw-tactical-quiet', 'Power Generation & Distribution', '30 kW Tactical Quiet Generator (lighter alternate)', 'MEP-805A, 60 Hz', 0, 1800, 0, NULL, NULL, NULL, 'Skid-mounted, own trailer/flatrack', 'Non-ISU / Own Trailer-Skid', 'Lighter/cheaper than the 60 kW set; still workable if only a partial load must ride through a FOB outage', 'Runs near or above 85% loading against the calculated full-site max load - not recommended for sustained full-load backup', 'MARCORSYSCOM 30kW TQG info sheet; see the loading-percentage flag on the Power & Thermal Budget tab.', 'marcorsyscom.marines.mil', 22),
  ('eq-24-pow-automatic-transfer-s', 'Power Generation & Distribution', 'Automatic Transfer Switch (ATS), FOB grid <-> generator', 'Standard tactical/COTS ATS rated for full-site load', 1, 120, 3, NULL, NULL, NULL, 'ISU-90', 'Container 3 - Power & Support', 'Seamless failover from FOB shore power to backup generator without manual switching - critical for a sensor that can lose tracking lock if power drops', 'Adds a component that itself must be sized/rated correctly and periodically tested', 'General COTS category; size to the Full-Site Max Electrical Load figure on the Power & Thermal Budget tab.', 'N/A - generic category', 23),
  ('eq-25-pow-power-distribution', 'Power Generation & Distribution', 'Power Distribution & Illumination System, Electrical (PDISE)', 'Army standard PDISE distribution box', 2, 150, 4, NULL, NULL, NULL, 'ISU-90', 'Container 3 - Power & Support', 'Standard Army load-center item; distributes FOB shore power or generator output to shelters/loads with breaker protection', 'Adds a cable-management burden; must be correctly grounded/bonded at each site to be safe', 'Estimated weight/volume - confirm against unit-specific PDISE TAMCN before procurement.', 'N/A - generic category', 24),
  ('eq-26-pow-rack-mount-online-d', 'Power Generation & Distribution', 'Rack-Mount Online (double-conversion) UPS', 'APC Smart-UPS SRT or ruggedized equivalent, 3 kVA', 4, 120, 3, NULL, NULL, NULL, 'ISU-90', 'Container 3 - Power & Support', 'Protects the sensor and antenna tracking electronics from generator transfer glitches/harmonics during FOB-to-generator failover - losing tracking lock mid-pass would cost the collection opportunity', 'Batteries add weight and have a finite service life/shelf life in austere climates', 'Commercial COTS; size per receiver/antenna-controller rack and confirm bridge runtime needed for generator auto-start.', 'N/A - generic category', 25),
  ('eq-27-env-zone-a-single-5-to', 'Environmental Control (HVAC)', 'ZONE A - Single 5-Ton (60,000 BTU) ECU, ops shelter + ECP (recommended)', 'Marine Corps standard 5-Ton ECU, 208 VAC 3-phase, shared via duct extension into the ECP', 1, 1100, 20, NULL, NULL, NULL, 'Skid/pallet, own transport recommended', 'Non-ISU / Own Trailer-Skid', 'Now that the sensor''s heat load lives in its own container (Zone B, below), this legacy default - previously flagged INSUFFICIENT for the combined load - comfortably covers the ops shelter + ECP alone with well over 100% margin. Also the most widely fielded ECU size in Army/Marine Corps inventories, simplest sustainment tail', 'Single unit, no N+1 redundancy - acceptable here since the ops floor isn''t the mission-critical heat-sensitive load the sensor is, but see the N+1 alternate below if continuous secure-space comfort is a hard requirement', 'MARCORSYSCOM ECU info sheet. See Power & Thermal Budget tab, Zone A, for the math showing this now works once the sensor is split out.', 'marcorsyscom.marines.mil', 26),
  ('eq-28-env-zone-a-dual-5-ton', 'Environmental Control (HVAC)', 'ZONE A - Dual 5-Ton ECU, N+1 pair (resiliency upsize alternate)', 'Marine Corps standard 5-Ton ECU x2, 208 VAC 3-phase', 0, 1100, 20, NULL, NULL, NULL, 'Skid/pallet, own transport recommended', 'Non-ISU / Own Trailer-Skid', 'Adds redundancy for the ops shelter/ECP the same way the sensor container gets N+1 - worth it if this secure space must stay continuously habitable regardless of a single ECU failure', 'Extra weight/cost for a zone that isn''t carrying the site''s single most heat-sensitive piece of equipment', 'MARCORSYSCOM ECU info sheet. Optional upsize, not the default - see Power & Thermal Budget tab Zone A.', 'marcorsyscom.marines.mil', 27),
  ('eq-29-env-zone-b-dual-72-000', 'Environmental Control (HVAC)', 'ZONE B - Dual 72,000 BTU/hr Vertical ECU, N+1 pair (sensor container, recommended)', 'ACT/Tekgard-type vertical wall-mount ECU (rigid-wall shelter cooling), integrated into the sensor ISU-90', 2, 700, 12, NULL, NULL, NULL, 'Mounted through the sensor container''s own wall - ships with it', 'Container 5 - Sensor Shelter', 'Vertical/wall-mount form factor is "perfect for rigid wall shelter cooling" per the vendor''s own category description - a natural fit for an ISU-90''s steel wall; sized so one unit alone exceeds the sensor''s MAX 12,900 W draw (not just typical) converted to BTU/hr, since the small sealed container has far less thermal buffering than the ops tent - see Power & Thermal Budget tab, Zone B', 'A tempting dual 46,000 BTU/hr pair falls just short of covering the max-draw requirement with only one unit running - shown explicitly on the Power & Thermal Budget tab as a cautionary comparison, the same ''insufficient N+1'' trap as the earlier dual-6-Ton case', '1-act.com Tekgard vertical ECU category description (12K/40K/46K/72K/96K BTU/hr sizes). Confirm exact model and container wall cutout/mounting kit once the sensor''s chassis and rack layout are finalized.', '1-act.com (Tekgard vertical ECU)', 28),
  ('eq-30-env-zone-b-single-72-0', 'Environmental Control (HVAC)', 'ZONE B - Single 72,000 BTU/hr Vertical ECU (no redundancy alternate)', 'ACT/Tekgard-type vertical wall-mount ECU', 0, 700, 12, NULL, NULL, NULL, 'Mounted through the sensor container''s own wall', 'Container 5 - Sensor Shelter', 'Simpler/lighter than the N+1 pair if the sensor''s own internal redundancy or a fast-swap spare policy substitutes for a second installed ECU', 'No N+1 redundancy on the single most heat-sensitive, mission-critical load in the design - generally not recommended', '1-act.com Tekgard vertical ECU category description. Listed only as a lower-cost, lower-resilience alternate.', '1-act.com (Tekgard vertical ECU)', 29),
  ('eq-31-pro-fully-rugged-laptop', 'Processing, Exploitation & Analysis Workstations', 'Fully-Rugged Laptop (ES operator console, threshold 4 concurrent seats)', 'Panasonic TOUGHBOOK 40 / 55', 4, 6, 0.5, NULL, NULL, NULL, 'ISU-90', 'Container 3 - Power & Support', 'MIL-STD-810 rated, modular xPAK expansion bays (GPS, extra I/O, encrypted SSD), up to ~36 hr battery, largest DoD install base', 'Premium price point vs. commercial rugged laptops; heavier than ultralight commercial notebooks', 'Panasonic TOUGHBOOK DSEI release; Military Toughbook DoD procurement guide. Sized to the 4 ES operators on console at once - the opposite-shift 4 operators use the same 4 seats/laptops on handover rather than needing their own set.', 'toughruggedlaptops.com', 30),
  ('eq-32-pro-fully-rugged-laptop', 'Processing, Exploitation & Analysis Workstations', 'Fully-Rugged Laptop (leadership shared workspace)', 'Panasonic TOUGHBOOK 40 / 55', 2, 6, 0.5, NULL, NULL, NULL, 'ISU-90', 'Container 3 - Power & Support', 'Same platform as the ES consoles for logistics commonality; gives the site commander and site enlisted leader independent screens at their shared desk', 'A second device family/config to track if a different, lighter-duty laptop is preferred for administrative/command use', 'Sized to the 2 leadership positions sharing one workspace across both shifts.', 'toughruggedlaptops.com', 31),
  ('eq-33-pro-rugged-rack-mount-an', 'Processing, Exploitation & Analysis Workstations', 'Rugged Rack-Mount Analysis Server (GPU-enabled)', 'Core Systems rugged rackmount server', 2, 70, 3, NULL, NULL, NULL, 'ISU-90', 'Container 3 - Power & Support', 'Meets/exceeds MIL-STD shock/vibration/EMI requirements, supports NVIDIA GPUs for AI-assisted signal analytics at the tactical edge for downlink signal processing/exploitation', 'Higher power draw and heat load than laptop-class processing - already reflected in the Power & Thermal Budget IT line', 'Core Systems rugged server product page. Sized to sensor data-processing throughput, not headcount, so unchanged by crew structure.', 'core-systems.com', 32),
  ('eq-34-net-hardened-tactical-et', 'Networking & IT Infrastructure', 'Hardened Tactical Ethernet Switch', 'MIL-spec rugged managed switch', 3, 8, 0.5, NULL, NULL, NULL, 'ISU-90', 'Container 3 - Power & Support', 'Provides VLAN-segmented backbone for sensor, antenna-control, and admin traffic; tolerates shock/vibration/temperature extremes', 'Higher cost than commercial-grade switches; needs a trained network operator to configure/maintain', 'General COTS category - confirm current authorized products list (APL) item with unit S6.', 'N/A - generic category', 33),
  ('eq-35-net-transit-case-server', 'Networking & IT Infrastructure', 'Transit-Case Server/Network Rack', 'SKB/Pelican-style rack-mount transit case, 12-16U', 2, 120, 8, NULL, NULL, NULL, 'ISU-90', 'Container 3 - Power & Support', 'Turns the shelter into a plug-and-play data closet; protects switches/servers/patch panels in transit', 'Rack cases are bulky even empty and eat into available container cube', 'Standard rugged-rack-case category; confirm rack unit count against actual IT load.', 'N/A - generic category', 34),
  ('eq-36-c2-ruggedized-large-for', 'C2 / Situational Awareness', 'Ruggedized Large-Format Display', '55" outdoor/rugged-rated monitor', 2, 90, 6, NULL, NULL, NULL, 'ISU-90', 'Container 3 - Power & Support', 'One shared display for the 4-operator ES console area, one at the leadership shared workspace - improves situational awareness over individual laptop screens for both groups', 'Large, awkward item that consumes disproportionate container cube for its weight', 'General COTS category; size/qty should be tuned to actual shelter floor plan.', 'N/A - generic category', 35),
  ('eq-37-com-multiband-manpack-ra', 'Communications & Backup Backhaul', 'Multiband Manpack Radio (ES team backup net)', 'AN/PRC-117G', 2, 16, 0.7, NULL, NULL, NULL, 'ISU-90', 'Container 3 - Power & Support', 'Fielded multiband/multimode manpack radio, standard Army voice/data backup net independent of the FOB LAN, sized to the 4-operator ES console shift', 'Line-of-sight range limitations without relay/retrans; separate crypto-fill/COMSEC management burden', 'Standard Army PRC-117G fielding; retained as a voice backup, not the site''s primary data path.', 'N/A - generic category', 36),
  ('eq-38-com-multiband-manpack-ra', 'Communications & Backup Backhaul', 'Multiband Manpack Radio (site command net, leadership workspace)', 'AN/PRC-117G', 2, 16, 0.7, NULL, NULL, NULL, 'ISU-90', 'Container 3 - Power & Support', 'Dedicated command net radios for the site commander and site enlisted leader, kept separate from the ES team''s operating net so command traffic and collection-team coordination don''t compete on the same channel', 'Doubles the radio/COMSEC-fill management burden versus a single shared net', 'Added specifically to meet the leadership positions'' stated communication requirement, distinct from the ES team''s backup net above.', 'N/A - generic category', 37),
  ('eq-39-com-backup-tactical-satc', 'Communications & Backup Backhaul', 'Backup Tactical SATCOM/VSAT Terminal', 'Manpack Ku/Ka-band VSAT terminal (commercial or PM Tactical Network)', 1, 55, 4, NULL, NULL, NULL, 'ISU-90', 'Container 3 - Power & Support', 'Restores network backhaul if the FOB grid/LAN connection is degraded, keeping ES reporting flowing to higher echelons', 'Any local RF transmitter needs a deliberate siting/EMI-separation check against the passive receive antennas on this site to avoid self-interference with the collection mission', 'Included per FOB-tied power/network posture. Coordinate physical siting with the antenna farm layout before emplacement.', 'N/A - generic category', 38),
  ('eq-40-cab-low-loss-rf-feed-run', 'Cabling & RF Interconnect', 'Low-Loss RF Feed Runs (antenna-to-sensor)', 'Low-loss coax or waveguide, short-run, per antenna', 3, 20, 1, NULL, NULL, NULL, 'ISU-90', 'Container 1 - Antenna & RF', 'Short, low-loss runs directly protect the G/T budget that the 9-12 dB SNR requirement depends on - every dB of feed loss here is a dB the antenna/LNA must make up', 'Constrains where the shelter can sit relative to each antenna; longer runs may force waveguide instead of coax at Ku/Ka', 'General RF-engineering principle (see G/T discussion, Overview tab). Confirm run lengths once the site layout is fixed.', 'N/A - generic category', 39),
  ('eq-41-cab-cat6-fiber-network-c', 'Cabling & RF Interconnect', 'CAT6/Fiber Network Cable & Patch Kit', 'Standard CAT6 + single-mode fiber patch kit', 1, 25, 2, NULL, NULL, NULL, 'ISU-90', 'Container 3 - Power & Support', 'Supports shelter-to-shelter and shelter-to-antenna-controller network backbone', 'Fiber terminations require trained technicians/field-splice kits for reliable connections', 'General IT-cabling category.', 'N/A - generic category', 40),
  ('eq-42-fur-folding-field-table', 'Furniture & Site Furnishings', 'Folding Field Table, ES Console (aluminum, rugged)', 'Standard Army folding field table', 4, 25, 2, NULL, NULL, NULL, 'ISU-90', 'Container 4 - Furniture & Site Support', 'Quick to set up/strike, standard NSN item, one table per concurrent ES operator seat', 'Bulky when stacked; folding hardware is a common failure/wear point in the field', 'Sized to the 4-seat ES console (threshold), not the full 8-operator roster, since only one shift is on console at a time.', 'N/A - generic category', 41),
  ('eq-43-fur-leadership-shared-wo', 'Furniture & Site Furnishings', 'Leadership Shared Workspace (2-position desk/table)', 'Standard Army folding field table, 2-position configuration', 1, 35, 3, NULL, NULL, NULL, 'ISU-90', 'Container 4 - Furniture & Site Support', 'One shared workspace for the site commander and site enlisted leader keeps their footprint separate from the ES console area while still being a single, compact addition to the shelter layout', 'A shared desk means the two leadership positions can''t both spread out large map/reference materials at once', 'Added specifically for the 2 leadership positions described as sharing one workspace.', 'N/A - generic category', 42),
  ('eq-44-fur-folding-field-chair', 'Furniture & Site Furnishings', 'Folding Field Chair', 'Standard Army folding field chair', 6, 10, 1, NULL, NULL, NULL, 'ISU-90', 'Container 4 - Furniture & Site Support', 'Lightweight, stackable, standard-issue comfort item for 8-12 hr shifts', 'Minimal ergonomic support for long analytic shifts compared to purpose-built task chairs', 'Sized to the 6-person max simultaneous occupancy (4 ES operators + 2 leadership).', 'N/A - generic category', 43),
  ('eq-45-fur-led-area-task-lighti', 'Furniture & Site Furnishings', 'LED Area/Task Lighting Kit', 'Standard tactical LED light set', 6, 15, 1, NULL, NULL, NULL, 'ISU-90', 'Container 4 - Furniture & Site Support', 'Low power draw (already reflected in the lighting/hotel-load line on the Power & Thermal Budget tab), instant-on, dimmable for light discipline', 'Battery-powered variants need a resupply/recharge plan; wired variants add another circuit to the PDISE', 'General COTS/Army lighting category; sized to shelter floor area, not headcount.', 'N/A - generic category', 44),
  ('eq-46-sto-transit-storage-case', 'Storage, Cases & Organization', 'Transit/Storage Cases (assorted sizes)', 'Pelican / Hardigg transit cases', 12, 25, 2.5, NULL, NULL, NULL, 'ISU-90', 'Container 4 - Furniture & Site Support', 'Waterproof/crushproof protection for spare antenna feed components and IT hardware between moves', 'Empty case weight/cube is a real tax on payload budget across a whole site''s worth of gear', 'General rugged-case category; trimmed slightly given fewer personal/workstation cases needed for a 6-seat, not 10-seat, shelter footprint.', 'N/A - generic category', 45),
  ('eq-47-for-perimeter-site-secur', 'Force Protection & Site Security', 'Perimeter/Site Security Lighting', 'Standard tactical perimeter lighting kit', 4, 20, 1.5, NULL, NULL, NULL, 'ISU-90', 'Container 4 - Furniture & Site Support', 'Improves site security and safety during hours-of-darkness antenna maintenance', 'Light discipline must be coordinated with the FOB''s existing perimeter security plan', 'General force-protection category.', 'N/A - generic category', 46),
  ('eq-48-for-site-cctv-camera-kit', 'Force Protection & Site Security', 'Site CCTV/Camera Kit', 'Standard COTS rugged CCTV kit', 4, 15, 1, NULL, NULL, NULL, 'ISU-90', 'Container 4 - Furniture & Site Support', 'Adds site-level monitoring for the antenna farm/shelter footprint without pulling personnel off collection duties', 'Requires its own network/recording infrastructure and cybersecurity accreditation to connect to Army networks', 'General COTS security category.', 'N/A - generic category', 47),
  ('eq-49-sup-antenna-mast-groundi', 'Support / Field Equipment', 'Antenna/Mast Grounding & Lightning Protection Kit', 'Standard grounding rod, strap, and bonding kit', 3, 30, 1, NULL, NULL, NULL, 'ISU-90', 'Container 4 - Furniture & Site Support', 'Protects personnel and sensitive antenna/sensor RF front ends from lightning strikes and static buildup - one kit per antenna pedestal', 'Effectiveness depends on soil conditions/ground resistance at the specific FOB site - must be verified on emplacement', 'General life-safety/grounding category; treat as mandatory for every mast/antenna pedestal, not optional.', 'N/A - generic category', 48),
  ('eq-50-sup-antenna-alignment', 'Support / Field Equipment', 'Antenna Alignment / Boresight Tool Kit', 'Standard optical/RF boresight and alignment tools', 1, 25, 2, NULL, NULL, NULL, 'ISU-90', 'Container 4 - Furniture & Site Support', 'Speeds initial antenna emplacement and verifies pointing accuracy before relying on autotrack', 'Requires a trained RF technician to use effectively', 'General satcom ground-station commissioning practice.', 'N/A - generic category', 49),
  ('eq-51-sup-portable-fire-exting', 'Support / Field Equipment', 'Portable Fire Extinguisher (ABC)', 'Standard 10-lb ABC extinguisher', 4, 10, 0.5, NULL, NULL, NULL, 'ISU-90', 'Container 4 - Furniture & Site Support', 'Required life-safety item near generators/power distribution and electronics; low weight/cube cost', 'Requires periodic inspection/recharge to remain mission-ready', 'Standard life-safety item, NSN-listed.', 'N/A - generic category', 50),
  ('eq-52-sup-rigging-tie-down', 'Support / Field Equipment', 'Rigging & Tie-Down / Tool Kit', 'Standard mechanic/rigger tool kit with tie-down straps', 2, 40, 2, NULL, NULL, NULL, 'ISU-90', 'Container 4 - Furniture & Site Support', 'Covers on-site troubleshooting, antenna guying, and load securing for onward movement without waiting on outside support', 'Adds weight that competes with mission equipment if oversized for the actual maintenance scope', 'General maintenance/rigging category.', 'N/A - generic category', 51),
  ('eq-53-sup-fuel-fluid-spill-kit', 'Support / Field Equipment', 'Fuel/Fluid Spill Kit', 'Standard HAZMAT spill-response kit', 1, 20, 1, NULL, NULL, NULL, 'ISU-90', 'Container 4 - Furniture & Site Support', 'Required for environmental compliance wherever backup generators/fuel are stored or run', 'Single-use consumables need periodic restocking after any real spill event', 'Standard environmental-compliance item.', 'N/A - generic category', 52);

insert into power_load_items (id, label, typical_w, max_w, qty, qty_editable, notes, sort_order) values
  ('sensor', 'Existing SIGINT/EW Sensor System (GFE)', 8000, 12900, 1, false, 'Fixed value provided by the sensor''s owning program - drives the rest of this budget.', 0),
  ('antenna-pedestal', 'Antenna Tracking Pedestal + Feed Electronics (per antenna)', 400, 800, 3, true, 'Servo/positioner motors, tracking controller, downconverters/LNAs. Engineering estimate - confirm against selected vendor datasheet once an antenna is down-selected.', 1),
  ('radome-compressor', 'Radome Inflation Compressor (intermittent - excluded from continuous hotel load)', 0, 0, 0, true, 'AirBeam-type radomes are pressurized once to ~55 psi and sealed behind a valve - no sustained electrical draw. Run the high-CFM compressor off the generator start-up margin rather than budgeting it as a steady-state load.', 2),
  ('it-load', 'Processing / Exploitation / C2 IT Load (workstations, servers, switches, displays)', 1250, 1800, 1, false, 'Aggregate of 4 ES-operator laptops + 2 leadership-workspace laptops, 2 GPU analysis servers, network gear, and 2 large-format displays, sized to the 6-person max simultaneous occupancy.', 3),
  ('lighting-hotel', 'Site Lighting & Hotel Loads', 1000, 1500, 1, false, 'General shelter lighting, small appliances, battery chargers.', 4),
  ('backup-comms', 'Backup Comms (manpack radios standby/keying, backup SATCOM terminal)', 100, 300, 1, false, 'Voice/data backup path independent of the FOB LAN; low duty cycle assumed.', 5);

insert into antenna_comparison (system, architecture, band_coverage, orbital_regimes, pack_form, acquisition, pros, cons, source, sort_order) values
  ('AvL Quad-Band Motorized Dish (1.8-2.4m family)', 'Mechanical dish, palletized quick-change feeds', 'C/X/Ku/Ka (one band live at a time; S-band not offered)', 'GEO, MEO, LEO, HEO', 'Segmented carbon-fiber reflector + cased feed pallets, tool-less', 'Commercial purchase / integrator', 'Field-swappable feed pallets let one dish cover 4 of the 5 required bands without a dedicated aperture per band; auto-acquisition controller; deployable by one person in under 15 minutes', 'Only one band live per dish at a time - true simultaneous cross-band coverage still needs multiple dishes; no native S-band pallet in the published line', 'digisat.org (AvL)', 0),
  ('Dolph Microwave / Comtech-MCT S-band-capable dish', 'Mechanical dish, fixed multi-band feed cluster', 'L/S/X/C/Ku/Ka/Q/V (Dolph) or UHF-V (Comtech-MCT)', 'LEO, MEO, HEO, GEO', 'Multi-case transportable set', 'Commercial purchase / integrator', 'Closes the S-band gap the AvL swap family leaves open; deep TT&C/earth-station heritage; TLE program-track plus autotrack', 'Feed is fixed/multi-band rather than swap-pallet based, so it doesn''t follow the same field-reconfigurable model as the AvL line - best used as the dedicated S-band member of the antenna set rather than the whole solution', 'dolphmicrowave.com', 1),
  ('Kymeta KuKa 8 Series (ESA flat panel)', 'Electronically steered array, no moving parts', 'Ku/Ka simultaneous, single aperture', 'GEO, MEO, LEO, HEO (electronic steering)', 'Low-profile flat panel', 'Commercial purchase, active DoD development (ONR contract)', 'No mechanical positioner or feed swap needed for Ku/Ka - electronic beam steering switches band and orbit simultaneously; ~44% smaller footprint than comparable multi-terminal setups per the vendor', 'Emerging capability (2026 development contract, not yet a fielded program of record); does not reach S/C/X', 'kymetacorp.com', 2),
  ('NexSat ACE (conformal ESA)', 'Electronically steered array, conformal/embedded', 'Ku/Ka', 'Electronic steering (regime coverage per Ku/Ka satellite architecture)', 'Conformal - mounts flush to a shelter/vehicle panel', 'Commercial purchase (newly unveiled 2026)', 'Could eliminate a separate pedestal footprint entirely for the Ku/Ka portion of the mission', 'Very new to market; limited independent track record or government fielding history to evaluate against', 'microwavejournal.com', 3),
  ('CPI Antenna Technologies MOCAT (2.4m)', 'Mechanical dish, flyaway', 'Published emphasis on X-band; other-band feed availability unconfirmed', 'Not specified in public material', 'Multi-case transportable set', 'Commercial purchase / integrator', 'Established earth-station manufacturer, shown at AFCEA specifically as a 2.4m MOCAT; shares design language with CPI''s 0.6-2.4m flyaway family', 'Note: CPI now also owns the former GD SATCOM Technologies brands (next row) - the two may not be independent competitors for a sourcing comparison', 'cpii.com (CPI)', 4),
  ('General Dynamics SATCOM Technologies / Prodelin 2.4m 4-Piece (now CPI SAT)', 'Mechanical dish, dual-axis tracking mount', 'C-Ka on the related 4.6m sibling model (palletized feeds); 2.4m variant band set not independently confirmed', 'Not specified in public material for the 2.4m variant', 'Multi-case transportable set', 'Commercial purchase / integrator', 'Deep VertexRSI/Gabriel/Prodelin TT&C heritage; sibling 4.6m model has field-swappable C-through-Ka feeds', 'Same corporate family as CPI (row above) as of the CPI SAT rebrand - confirm brand/business-unit separation before treating as a separate bid', 'digisat.org (GD/CPI SAT)', 5),
  ('Viasat 2.4m-class ISR Earth Station Antenna', 'Mechanical dish, full/limited-motion earth station', 'Not broken out by model in public material (vendor covers 2.4m-24m range)', 'GEO, HEO, MEO, LEO (vendor-stated)', 'Multi-case/transportable at the small end of the range', 'Commercial purchase / integrator', 'Vendor explicitly markets this line for ISR missions; hundreds of remote-sensing antennas fielded worldwide', 'No specific 2.4m or 3m model/spec sheet published - needs a direct vendor quote to pin down size-specific performance', 'viasat.com', 6),
  ('Sat-Lite Technologies 2431/2432 (2.4m, Agilis carbon fiber)', 'Mechanical dish, motorized flyaway', 'C/X/Ku confirmed; Ka/S not confirmed on this line', 'Not specified in public material', '9-piece segmented reflector, 6 cases + 1 RF case/band', 'Commercial purchase / integrator', 'Assembles in 15 minutes; won a $9.9M US Army COTS tactical-aperture contract in July 2026 (Aberdeen Proving Ground) - fresh, direct Army sustainment relevance', 'Published band coverage doesn''t confirm Ka or S on this specific line', 'digisat.org (Sat-Lite)', 7),
  ('Ultra I&C FA-370 (3.7m, above stated 3m ceiling)', 'Mechanical dish, quad-band clip-in feed cartridges', 'C/X, Ku/DBS, Ka via 4-piece segmented feed arm (no native S-band)', 'Not specified (GEO-class earth-station design; tracking/orbital-regime capability not detailed in the public datasheet)', '5 cases, ~470 kg (~1,036 lb) total, tool-free <30 min assembly', 'Commercial purchase / integrator', 'Largest true flyaway aperture reviewed (3.7m) - materially higher gain (45.3-58.4 dBi depending on band) than 2.4m-class systems, which directly helps the SNR margin; linear polarization standard with circular optional; MIL-STD-810G certified, WGS/SkyNet/XTAR/Inmarsat compliant', '0.7m over the stated 3m ceiling, and heavier/bulkier than the 2.4m-class competitors; no native S-band feed cartridge published, same gap as the AvL/GD swap families', 'ultra-ic.com (datasheet PDF)', 8),
  ('Comtech TCS (Telecommunications Systems) - low confidence, please confirm', 'Protected terminal integration (P-COTM), not primarily a dish manufacturer', 'Not specified - this division builds terminal electronics/integration more than reflector antennas', 'N/A', 'N/A - vendor RFI needed', 'Commercial purchase / integrator', 'Established defense-terminal integrator with a track record on protected/military SATCOM-on-the-move programs', 'May not be the company intended by "TCS" - several similarly-abbreviated firms exist in this space. This row should be corrected once confirmed', 'microwavejournal.com', 9);

insert into radome_comparison (system, structure_type, continuous_power, setup_time, pros, cons, source, sort_order) values
  ('Walton Portable Radome', 'Rigid, self-supporting', 'No', '< 1 hour, tool-free', 'Twice the wind load rating of comparable inflatables; smallest size is airline-baggage-checkable; no standing power draw to fail', 'Heavier pack weight than an inflatable of the same aperture', 'milsatmagazine.com', 0),
  ('HDT AirBeam RaDome - pressurized & sealed, not continuously blown', 'Air-supported (inflatable envelope, ~55 psi, sealed via valve)', 'No - sealed after inflation (intermittent compressor only)', '< 30 min for smaller units', 'Lowest pack weight/volume of the three options; minimally attenuates RF; sealed valve architecture means no standing blower load or blower-failure risk once inflated', 'Needs a high-CFM air source for initial inflation and occasional top-off - an intermittent, not continuous, requirement, but still real kit to carry', 'adsinc.com (HDT Global)', 1),
  ('Alaska Defense SkyDome-style space frame', 'Rigid, geodesic panel', 'No', 'Longest - semi-permanent assembly', 'Most robust weather protection for extended, fixed-site deployments', 'Assembly complexity and time work against a ''rapidly deployable'' requirement', 'alaskadefense.com', 2);
